# Generated by Django 6.0 on 2026-01-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.TextField(null=True),
        ),
    ]
