# Generated by Django 6.0 on 2026-01-18 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('sale_starts_at', models.DateTimeField()),
                ('sale_ends_at', models.DateTimeField()),
                ('event_starts_at', models.DateTimeField()),
                ('event_ends_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_url', models.URLField(blank=True, null=True)),
                ('waitlist_url', models.URLField(blank=True, null=True)),
                ('template', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=8)),
                ('url', models.URLField(blank=True, null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_link_id', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_message_title', models.CharField(blank=True, max_length=255, null=True)),
                ('welcome_message_text', models.TextField(blank=True, null=True)),
                ('checklist', models.TextField(blank=True, null=True)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('limit_quantity', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'ticket_types',
                'ordering': ['created_at'],
            },
        ),
    ]
