# Generated by Django 6.0 on 2026-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_icon_event_location_url_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTypeOptions',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('select', 'select')], default='select', max_length=32)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ticket_type_options',
            },
        ),
        migrations.AddField(
            model_name='tickettype',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
