# Generated by Django 6.0 on 2026-01-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_tickettypeoptions_tickettype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTypeChecklist',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('select', 'select'), ('limited_select', 'limited_select'), ('text', 'text'), ('link', 'link')], default='select', max_length=32)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ticket_checklists',
                'ordering': ['created_at'],
            },
        ),
    ]
