# Generated by Django 6.0 on 2026-01-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_tickettypechecklist'),
        ('tickets', '0004_ticketchecklistanswers_delete_ticketoptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketTypeOptions',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['index', '-created_at']},
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='options',
            new_name='checklists',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='checklist',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
