# Generated by Django 6.0 on 2026-01-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_delete_tickettypeoptions_alter_event_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='template',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='stripe_payment_link_id',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_free_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='limit_per_user',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tickettypechecklist',
            name='type',
            field=models.CharField(choices=[('select', 'select'), ('text', 'text'), ('link', 'link')], default='select', max_length=32),
        ),
    ]
