# Generated by Django 6.0 on 2026-01-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='is_free_event',
        ),
        migrations.AddField(
            model_name='event',
            name='is_free_event',
            field=models.BooleanField(default=False),
        ),
    ]
