# Generated by Django 6.0 on 2026-01-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_tickettype_is_free_event_event_is_free_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='stripe_product_id',
            new_name='stripe_price_id',
        ),
    ]
