# Generated by Django 6.0 on 2026-01-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_stripe_product_id_tickettype_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='special_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
