# Generated by Django 6.0 on 2026-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_tickettype_special_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_free_event',
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
