# Generated by Django 6.0 on 2026-01-21 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_tickettypechecklist'),
        ('tickets', '0003_ticketoptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketChecklistAnswers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.JSONField(blank=True, default=str, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tickettypechecklist')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_checklist_answers',
                'ordering': ['created_at'],
                'unique_together': {('ticket', 'user', 'checklist')},
            },
        ),
        migrations.DeleteModel(
            name='TicketOptions',
        ),
    ]
