# Generated by Django 6.0 on 2026-01-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketchecklistanswers_delete_ticketoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
